micronaut:
  application:
    name: casaDoCodigo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/cdc?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
